### ISSUE TITLE
Where are font-lock-profiler and font-lock-regression-suite

### ISSUE THREAD

**Issue by tarsius** [Lindydancer/font-lock-studio#2]
These two features are required by the tests for this package, but I cannot find them anywhere.

**Comment by Lindydancer** [comment]
Hi!

Wow, you're fast! I just pushed the change a couple of days ago and right
now I'm in the process of publishing my new font-lock tools on Melpa.

In the mean time, you can download them from:

  https://github.com/Lindydancer/font-lock-profiler
  https://github.com/Lindydancer/font-lock-regression-suite

    -- Anders

**Comment by tarsius** [comment]
> Wow, you're fast!

It's semi-automated. After updating the packages on the [Emacsmirror](https://emacsmirror.org) I also regenerate the lists in [this file](https://emacsmirror.net/stats/issues.html) and try to deal with new issues.

Thanks for making these repositories available.

**Comment by tarsius** [comment]
After adding these two packages, there are two new issues: `font-lock-regression-suite` provides the features `files` and `remote-wildcards`. It looks like you are adding these two libraries for testing purposes. You should make sure they don't end up on the `load-path` by adding the file `src/.nosearch` (see `normal-top-level-add-subdirs-to-load-path`).

**Comment by Lindydancer** [comment]
On Sun, Feb 5, 2017 at 12:31 PM, Jonas Bernoulli <notifications@github.com>
wrote:

> After adding these two packages, there are two new issues:
> font-lock-regression-suite provides the features files and
> remote-wildcards. It looks like you are adding these two libraries for
> testing purposes. You should make sure they don't end up on the load-path
> by adding the file src/.nosearch (see normal-top-level-add-subdirs-
> to-load-path).
>

Ah, I see... Actually, the line you're referring to comes from "files.el"
which is part of core Emacs. `font-lock-regression-suite' has a local copy
of it, it is used to check that syntax highlighting of elisp is done
properly.

I'll add .nosearch files to all non-elisp directories.

Thanks!

    -- Anders

**Comment by Lindydancer** [comment]
Hi!

I just pushed the update, please check if it solves your problem.

    -- Anders

**Comment by tarsius** [comment]
That's about the opposite of what I was hoping for ;-)
1. It doesn't matter if a directory that *does not* contain any elisp files does not contain `.nosearch`. Emacs won't add it to the `load-path` either way.
2. The reason why I suggested that you add `.nosearch` is this:

> `font-lock-regression-suite' has a local copy of it, it is used to check that syntax highlighting of elisp is done properly.

That copy should *not* end up on the `load-path`. It was taken from some Emacs version and is not necessarily compatible with other versions, and/or lacks bug fixes or new features.

(I suggested `src/.nosearch` instead of `src/elisp/Emacs/.nosearch` because I got the impression that other elisp files that should not end up on the `load-path` might be created in other directories in the future).

**Comment by Lindydancer** [comment]
Hi!

I agree that the local copy of `files.el' should not end up in the load
path, for obvious reasons.

> That's about the opposite of what I was hoping for ;-)


In the 0.0.1 release, I included `src/.nosearch' as you suggested. I also
ran `normal-top-level-add-subdirs-to-load-path' and checked it neither add
"src" nor any of its subdirectories to the load-path.

I thought this was what you was asking for. Can you check again, and if it
still doesn't work, advice me on how to fix it.

    -- Anders

**Comment by tarsius** [comment]
> I thought this was what you was asking for.

Yes indeed. This confused me:

> I'll add .nosearch files to all **non-elisp** directories.

But looking at the commit I can see that you added the file I suggested. (I haven't run an Emacsmirror update yet, but that will do the trick for sure.)

Thanks!
